ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopify.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopify/urls.py
from django.urls import path
from . import views

app_name = 'shopify'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('details/', views.details, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
    path('register/', views.register, name='register'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.custom_logout, name='logout'),
    path('updateItem/', views.updateItem, name='updateItem'),
    path('processOrder/', views.processOrder, name='processOrder')

    
]

shopify/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    category_name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.category_name

class Product(models.Model):
    Category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    product_title = models.CharField(max_length=30, null=True)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    description = models.CharField(max_length=255,null=True)
    sizes = models.CharField(max_length=10, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], null=True, blank=True)
    colors = models.CharField(max_length=20, null=True, blank=True)
    digital = models.BooleanField(default=False,null=True, blank=False)
    trendy = models.BooleanField(default=False,null=True, blank=False)
    image = models.ImageField(upload_to='media/', default='profile.png')

    def __str__(self):
        return self.product_title


    #  correcting image error when an image is deleted in other products
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except Exception as e:
            print(f"Error accessing image URL: {e}")
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200,null=True)
    def __str__(self):
        return str(self.id)
    
    @property
    def shipping_details(self):
        shipping_details = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping_details = True
        return shipping_details



    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total



    # @property
    # def get_total_payment(self):
    #     orderitems = self.orderitem_set.all()
    #     total = sum([item.get_total for item in orderitems])
    #     return total

class Shipping(models.Model):
    shipping_cost = models.DecimalField(max_digits=7,decimal_places=2)
    
    def __str__(self):
      return str(self.id)

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    mobile = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.address


class homeCaurosel(models.Model):
    text1 = models.CharField(max_length=200, null=True)
    text2 = models.CharField(max_length=200, null=True)
    btn_text = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='media/', default='profile.png')

    def __str__(self):
       return str(self.id)


class homeCollections(models.Model):
    heading1 = models.CharField(max_length=200, null=True)
    heading2 = models.CharField(max_length=200, null=True)
    btn_text = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='media/', default='profile.png')

    def __str__(self):
       return str(self.id)

shopify/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

shopify/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.db.models import Count
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from . forms import CreateUserForm
import json
from .models import *
import datetime
import random
from . utils import cookieCart, cartData, guestOrder


# Create your views here.
def home(request):
    trendy_products = Product.objects.filter(trendy=True)
    image_caurosels = homeCaurosel.objects.all()
    collections = homeCollections.objects.all()

    # Shuffle the collection items randomly
    shuffled_collections = list(collections)
    random.shuffle(shuffled_collections)
    # Take the first two items
    selected_collections = shuffled_collections[:2]

    # Fetch all categories and their associated products, limit to 6 categories
    categories_with_products = (
        Category.objects.annotate(num_products=Count('product'))
        .filter(num_products__gt=0)
        .prefetch_related('product_set')
        .order_by('?')[:6]
    )

    # get data from utils.py 
    data = cartData(request)
    # shipping = data['shipping']
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']


    context = {
        'cartItems': cartItems,
        'items':items,
        'order': order,
        'trendy_products': trendy_products,
        'collections': selected_collections,
        'image_caurosels': image_caurosels,
        'categories_with_products': categories_with_products,
        'name':'home',
    }
    return render(request, 'index.html',context)

def shop(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    # get data from utils.py 
    data = cartData(request)
    shipping = data['shipping']
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context ={
        'cartItems': cartItems,
        'items':items,
        'order': order,
        'categories': categories,
        'products': products,
        'name':'shop'
    }
    return render(request, 'shop.html',context)

def details(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'name':'detail'
    }
    return render(request, 'detail.html',context)

def cart(request):
    # get data from utils.py 
    data = cartData(request)
    shipping = data['shipping']
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    
    context = {
     'cartItems': cartItems,
     'items':items,
     'order': order,
     'shipping': shipping,
     'name':'cart' }
    return render(request, 'cart.html',context)

def checkout(request):
     # get data from utils.py 
    data = cartData(request)
    shipping = data['shipping']
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {
        'cartItems': cartItems,
        'items':items,
        'order': order,
        'shipping': shipping,
        'name':'checkout'
    }

    return render(request, 'checkout.html',context)

def contact(request):


    # get data from utils.py 
    data = cartData(request)
    cartItems = data['cartItems']

    
    context = {
        'cartItems': cartItems,
        'name':'checkout'
    }
    return render(request, 'contact.html',context )

def signin(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request,'Login Successfully')
            return redirect('shopify:home')
          


    # get data from utils.py 
    data = cartData(request)
    cartItems = data['cartItems']
    
    context = {
        'cartItems': cartItems,
        'name':'signin'
    }
    return render(request, 'signin.html',context)

def register(request):
    # register a new user
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully. You can now log in.')
            # Redirect to a success page or login page
            return redirect('shopify:signin')
        # else:
            messages.error(request, 'Error creating your account. Please correct the errors below.')

    # get data from utils.py 
    data = cartData(request)
    cartItems = data['cartItems']
    
    context = {
        'form': form,
        'cartItems': cartItems,
        'name':'register'
    }
    return render(request, 'register.html',context )

def custom_logout(request):
    logout(request)
    # Add any additional logic you want to perform on logout
    messages.success(request, 'Logout Successful')
    return redirect('shopify:home') 


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    
    return JsonResponse('item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
       

    else:
        customer, order = guestOrder(request, data)
    
    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    order.complete = True
    order.save()

    if order.shipping_details == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            mobile = data['shipping_details']['mobile'],
            address = data['shipping_details']['address'],
            city = data['shipping_details']['city'],
            state = data['shipping_details']['state'],
            zipcode = data['shipping_details']['zipcode'],

        )
    return JsonResponse('payment submited..', safe=False)

shopify/templates/cart.html
{% extends 'common.html'%}
{% load static %}

{% block title %}cart{% endblock %}
{% block content%}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Shopping Cart</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Shopping Cart</p>
        </div>
    </div>
</div>
<!-- Page Header End -->


<!-- Cart Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for item in items %}
                    <tr>
                        <td class="align-middle"><img src="{{item.product.image.url}}" alt="" style="width: 50px;"></td>
                        <td class="align-middle">Ksh.{{item.product.price|floatformat:2}}</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button data-product="{{item.product.id}}" data-action="remove" class="btn btn-sm btn-primary  update-cart" >
                                    <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary text-center" value="{{item.quantity}}">
                                <div class="input-group-btn">
                                    <button data-product="{{item.product.id}}" data-action="add" class="btn btn-sm btn-primary update-cart">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">Ksh.{{item.get_total}}</td>
                        <td class="align-middle"><button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-5" action="">
                <div class="input-group">
                    <input type="text" class="form-control p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        <h6 class="font-weight-medium">Ksh.{{order.get_cart_total|floatformat:2}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">Ksh.{{shipping.shipping_cost|floatformat:2}}</h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        <h5 class="font-weight-bold">Ksh.{{ order.get_cart_total|add:shipping.shipping_cost|floatformat:2 }}</h5>
                    </div>
                    <button class="btn btn-block btn-primary my-3 py-3" ><a href="{% url 'shopify:checkout'%}" style="text-decoration: none; color: white;">Proceed To Checkout</a></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->
{% endblock %}

shopify/templates/contact.html
{% extends 'common.html'%}
{% load static %}

{% block title %}contact{% endblock %}
{% block content%}

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Contact Us</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Contact</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Contact For Any Queries</span></h2>
        </div>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form">
                    <div id="success"></div>
                    <form name="sentMessage" id="contactForm" novalidate="novalidate">
                        <div class="control-group">
                            <input type="text" class="form-control" id="name" placeholder="Your Name"
                                required="required" data-validation-required-message="Please enter your name" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="email" class="form-control" id="email" placeholder="Your Email"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="text" class="form-control" id="subject" placeholder="Subject"
                                required="required" data-validation-required-message="Please enter a subject" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea class="form-control" rows="6" id="message" placeholder="Message"
                                required="required"
                                data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <h5 class="font-weight-semi-bold mb-3">Get In Touch</h5>
                <p>Justo sed diam ut sed amet duo amet lorem amet stet sea ipsum, sed duo amet et. Est elitr dolor elitr erat sit sit. Dolor diam et erat clita ipsum justo sed.</p>
                <div class="d-flex flex-column mb-3">
                    <h5 class="font-weight-semi-bold mb-3">Store 1</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
                <div class="d-flex flex-column">
                    <h5 class="font-weight-semi-bold mb-3">Store 2</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock %}

shopify/templates/index.html
{% extends 'common.html'%}
{% load static %}


{% block title %}home{% endblock %}
{% block content %}

    

    <!-- Featured Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
          <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div
              class="d-flex align-items-center border mb-4"
              style="padding: 30px"
            >
              <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
              <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div
              class="d-flex align-items-center border mb-4"
              style="padding: 30px"
            >
              <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
              <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div
              class="d-flex align-items-center border mb-4"
              style="padding: 30px"
            >
              <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
              <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div
              class="d-flex align-items-center border mb-4"
              style="padding: 30px"
            >
              <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
              <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
          </div>
        </div>
      </div>
      <!-- Featured End -->
  
      <!-- Categories Start -->
      <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
          {% for category in categories_with_products %}
          <div class="col-lg-4 col-md-6 pb-1">
            <div
              class="cat-item d-flex flex-column border mb-4"
              style="padding: 30px"
            >
              <p class="text-right">{{ category.product_set.count }} Products</p>
              {% if category.product_set.first %}
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                <img class="img-fluid" src="{{ category.product_set.first.image.url }}" alt="" />
              </a>
              {% endif %}
              <h5 class="font-weight-semi-bold m-0">{{ category.category_name }}</h5>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
      <!-- Categories End -->
  
      <!-- Offer Start -->
      <div class="container-fluid offer pt-5">
        <div class="row px-xl-5">
          {% for collection in collections%}
          <div class="col-md-6 pb-4">
            <div
              class="position-relative bg-secondary text-center text-md-right text-white mb-2 py-5 px-5"
            >
              <img src="{{collection.image.url}}" alt="" />
              <div class="position-relative" style="z-index: 1">
                <h5 class="text-uppercase text-primary mb-3">
                  {{collection.heading1}}
                </h5>
                <h1 class="mb-4 font-weight-semi-bold">{{collection.heading2}}</h1>
                <a href="{% url 'shopify:shop'%}" class="btn btn-outline-primary py-md-2 px-md-3"
                  >Shop Now</a
                >
              </div>
            </div>
          </div>
          {% endfor%}
        </div>
      </div>
      <!-- Offer End -->
  
      <!-- Products Start -->
      <div class="container-fluid pt-5">
        <div class="text-center mb-4">
          <h2 class="section-title px-5">
            <span class="px-2">Trandy Products</span>
          </h2>
        </div>
        <div class="row px-xl-5 pb-3">
          {% for product in trendy_products %}
          <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
              <div
                class="card-header product-img position-relative overflow-hidden bg-transparent border p-0"
              >
                <img
                  class="img-fluid w-100"
                  src="{{ product.image.url }}"
                  alt="{{ product.product_title }}"
                />
              </div>
              <div
                class="card-body border-left border-right text-center p-0 pt-4 pb-3"
              >
                <h6 class="text-truncate mb-3">{{ product.product_title }}</h6>
                <div class="d-flex justify-content-center">
                  <h6>Ksh.{{ product.price|floatformat:2 }}</h6>
                </div>
              </div>
              <div
                class="card-footer d-flex justify-content-between bg-light border"
              >
                <a href="" class="btn btn-sm text-dark p-0"
                  ><i class="fas fa-eye text-primary mr-1"></i>View Detail</a
                >
                <button data-product="{{product.id}}" data-action="add" class="btn btn-sm text-dark p-0 update-cart"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</button>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <!-- Products End -->
  
      <!-- Subscribe Start -->
      <div class="container-fluid bg-secondary my-5">
        <div class="row justify-content-md-center py-5 px-xl-5">
          <div class="col-md-6 col-12 py-5">
            <div class="text-center mb-2 pb-2">
              <h2 class="section-title px-5 mb-3">
                <span class="bg-secondary px-2">Stay Updated</span>
              </h2>
              <p>
                Be the first to know about new arrivals and limited-time offers that 
                allow you to refresh your wardrobe without breaking the bank.
              </p>
            </div>
            <form action="">
              <div class="input-group">
                <input
                  type="text"
                  class="form-control border-white p-4"
                  placeholder="Email Goes Here"
                />
                <div class="input-group-append">
                  <button class="btn btn-primary px-4">Subscribe</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- Subscribe End -->
  
      <!-- Vendor Start -->
      <div class="container-fluid py-5">
        <div class="row px-xl-5">
          <div class="col">
            <div class="owl-carousel vendor-carousel">
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-1.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-2.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-3.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-4.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-5.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-6.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-7.jpg' %}" alt="" />
              </div>
              <div class="vendor-item border p-4">
                <img src="{% static 'img/vendor-8.jpg' %}" alt="" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Vendor End -->
{% endblock%}

shopify/templates/signin.html
{% extends 'common.html' %}
{% load static %}

{% block title %}login{% endblock %}
{% block content %}
 <!-- Page Header Start -->
 <div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Login</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Login</p>
        </div>
    </div>
</div>
<!-- Page Header End -->

 <div class="form">
    <div class="container">
        <h2 class="text-center mb-4">Login Form</h2>
        <form style="width: 70%; margin: auto;" method="POST" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="UserName" class="form-label">UserName</label>
                <input type="text"name="username" class="form-control" required>   
            </div>
        
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" name="password" required> 
            </div>
            <button type="submit" class="btn btn-lg btn-block btn-primary mb-3">Login</button>
            <p class="text-center">Don't have account?<a href="{% url 'shopify:register'%}">Register here</a></p>
        </form>
    </div>
    
 </div>
{% endblock %}